<div class="span8 offset2">
    <h3> Nuevo Usuarios</h3>
    <?php View::content(); ?>
    <form class="form-horizontal" method="post">
            <div class="control-group">
            <label class="control-label">Cédula:</label>
            <div class="controls">

                <?php echo Registro::cmbNac('adulto.nac', 'class="span1"'),' ',Registro::number('adulto.cedula', 'class="span2"'), Form::hidden('adulto.id'); ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Credencial:</label>
            <div class="controls">

                <?php echo Registro::number('adulto.credencial', 'class="span2"'); ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Primer Nombre:</label>
            <div class="controls">

                <?php echo Form::text('adulto.primer_nombre', 'class="span2 req"'); ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Segundo Nombre:</label>
            <div class="controls">

                <?php echo Form::text('adulto.segundo_nombre', 'class="span2"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Primer Apellido:</label>
            <div class="controls">

                <?php echo Form::text('adulto.primer_apellido', 'class="span2 req"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Segundo Apellido:</label>
            <div class="controls">

                <?php echo Form::text('adulto.segundo_apellido', 'class="span2"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Correo Electrónico:</label>
            <div class="controls">

                <?php echo Form::text('adulto.email', 'class="span2"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Clave:</label>
            <div class="controls">

                <?php echo Form::text('adulto.nueva_clave', 'class="span2"', ''), Form::hidden('adulto.clave'); ; ?>

            </div>
        </div>

        <?php View::partial('adultos/region', null, array('nivel'=>$nivel, 'region'=>$adulto->region_id, 'adulto'=>$adulto)); ?>

        <?php View::partial('adultos/distrito', null, array('nivel'=>$nivel, 'region'=>$adulto->region_id, 'distrito'=>$adulto->distrito_id, 'adulto'=>$adulto)); ?>

        <?php View::partial('adultos/grupos', null, array('nivel'=>$nivel, 'distrito'=>$adulto->distrito_id, 'grupo'=>$adulto->grupos_id, 'adulto'=>$adulto)); ?>

        <?php View::partial('adultos/ramas', null, array('nivel'=>$nivel, 'grupo'=>$adulto->grupos_id, 'adulto'=>$adulto)); ?>

        <button class="btn btn-primary" id="btnRegistrar">Registrar</button>
    </form>
</div>
<?php echo Tag::js('form'); ?>