<div class="span8 offset2">
    <h3> Nuevo Usuarios</h3>
    <?php View::content(); ?>
    <form class="form-horizontal" method="post">
            <div class="control-group">
            <label class="control-label">Cédula:</label>
            <div class="controls">

                <?php echo Registro::cmbNac('adulto.nac', 'class="span1"'),' ',Registro::number('adulto.cedula', 'class="span2"'); ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Credencial:</label>
            <div class="controls">

                <?php echo Registro::number('adulto.credencial', 'class="span2"'); ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Primer Nombre:</label>
            <div class="controls">

                <?php echo Form::text('adulto.primer_nombre', 'class="span2 req"'); ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Segundo Nombre:</label>
            <div class="controls">

                <?php echo Form::text('adulto.segundo_nombre', 'class="span2"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Primer Apellido:</label>
            <div class="controls">

                <?php echo Form::text('adulto.primer_apellido', 'class="span2 req"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Segundo Apellido:</label>
            <div class="controls">

                <?php echo Form::text('adulto.segundo_apellido', 'class="span2"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Correo Electrónico:</label>
            <div class="controls">

                <?php echo Form::text('adulto.email', 'class="span2"'); ?>

            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Clave:</label>
            <div class="controls">

                <?php echo Form::text('adulto.clave', 'class="span2"'); ?>

            </div>
        </div>

        <?php print Session::get('region_id'); View::partial('adultos/region', null, array('nivel'=>$nivel, 'region'=>Session::get('region_id'))); ?>

        <?php $estructura = ($nivel < 2)?null:$estructura; View::partial('adultos/distrito', null, array('nivel'=>$nivel, 'region'=>$estructura, 'distrito'=>Session::get('distrito_id'))); ?>

        <?php $estructura = ($nivel < 3)?null:$estructura; View::partial('adultos/grupos', null, array('nivel'=>$nivel, 'distrito'=>$estructura, 'grupo'=>Session::get('grupos_id'))); ?>

        <?php $estructura = ($nivel < 4)?null:$estructura; View::partial('adultos/ramas', null, array('nivel'=>$nivel, 'grupo'=>Session::get('grupos_id'))); ?>

        <button class="btn btn-primary" id="btnRegistrar">Registrar</button>
    </form>
</div>
<?php echo Tag::js('form'); ?>