<div class="navbar">
	<div class="navbar-inner">
		<a href="<?php ?>" class="brand"><?php echo APP_NAME; ?></a>
		<ul class="nav pull-right">
			<li><?php echo Html::link('dashboard/', 'Dashboard', 'title="Panel de Principal"') ?></li>
			<li><?php echo Html::link('pages/show/kumbia/status/', 'Usuarios', 'title="Ver configuración de la aplicación"') ?></li>
			<li><?php echo Html::link('pages/show/kumbia/status/', 'Jovenes', 'title="Ver configuración de la aplicación"') ?></li>
			<li><?php echo Html::link('pages/show/kumbia/status/', 'Reportar', 'title="Ver configuración de la aplicación"') ?></li>
			<li><?php echo Html::link('pages/show/kumbia/status/', 'Ajustes', 'title="Panel de Ajustes"') ?></li>
			<li><?php echo Html::link('pages/show/kumbia/status/', 'Soporte', 'title="Reportar Fallas y Solicitar Soporte"') ?></li>
			<li><?php echo Html::link('salir/', 'Salir', 'title="Salir del Sistema"') ?></li>
		</ul>
	</div>
</div>