<div class="navbar hidden-print">
    <div class="navbar-inner navbar-scouts">

    <div class="cintillo">
        <img src="<?php echo PUBLIC_PATH; ?>/img/logo.jpg" class="pull-left">
        <div class="marca">
            <span id="trademark">SCOUTS<sup>&reg;</sup></span>
            <br/>
            <span id="pais">Venezuela</span>
        </div>

        <div class="complemento">
            Organización Mundial del Movimiento Scout<br/>
            Región Interamericana<br/>
            Asociación de Scouts de Venezuela<br/>
        </div>
    </div>
    <a href="<?php ?>" class="brand"><?php echo APP_NAME; ?></a>
    <ul class="nav navbar-nav pull-right">
        <li><?php echo Html::link('dashboard/', '<i class="icon-dashboard"></i> Dashboard') ?></li>
        <li><?php echo Html::link('jovenes/', '<i class="icon-group"></i> Jovenes') ?></li>
        <li><?php echo Html::link('actividades/', '<i class="icon-flag"></i> Actividades') ?></li>
        <li><?php echo Html::link('reportar/', '<i class="icon-calendar"></i> Reportar') ?></li>
        <li><?php echo Html::link('reportar/informe', '<i class="icon-bar-chart"></i> Informe') ?></li>
        <!-- <li><?php echo Html::link('soporte/', '<i class="icon-wrench"></i> Soporte') ?></li> -->
        <?php if ( Session::get('nivel') <= 4 ): ?>
        <li><?php echo Html::link('usuarios/', '<i class="icon-male"></i> Usuarios') ?></li>
        <?php endif; ?>
        <?php if ( Session::get('nivel') == 0 ): ?>
        <li><?php echo Html::link('ajustes/', '<i class="icon-cogs"></i> Ajustes') ?></li>
        <?php endif; ?>
        <li><?php echo Html::link('salir/', '<i class="icon-off"></i> Salir') ?></li>
    </ul>
</div>
</div>