<div class="navbar">
	<div class="navbar-inner">
		<a href="<?php ?>" class="brand"><?php echo APP_NAME; ?></a>
		<ul class="nav pull-right">
			<li><?php echo Html::link('dashboard/', '<i class="icon-dashboard"></i> Dashboard', 'title="Panel de Principal"') ?></li>
			<li><?php echo Html::link('jovenes/', '<i class="icon-group"></i> Jovenes', 'title="Jóvenes Scouts"') ?></li>
			<li><?php echo Html::link('actividades/', '<i class="icon-flag"></i> Actividades', 'title="Crear Actividades"') ?></li>
			<li><?php echo Html::link('reportar/', '<i class="icon-calendar"></i> Reportar', 'title="Reportar Actividades"') ?></li>
			<!-- <li><?php echo Html::link('soporte/', '<i class="icon-wrench"></i> Soporte', 'title="Reportar Fallas y Solicitar Soporte"') ?></li> -->
			<?php if ( Session::get('nivel') <= 4 ): ?>
			<li><?php echo Html::link('usuarios/', '<i class="icon-male"></i> Usuarios', 'title="Usuario de la Aplicación"') ?></li>
			<?php endif; ?>
			<?php if ( Session::get('nivel') == 0 ): ?>
			<li><?php echo Html::link('ajustes/', '<i class="icon-cogs"></i> Ajustes', 'title="Panel de Ajustes"') ?></li>
			<?php endif; ?>
			<li><?php echo Html::link('salir/', '<i class="icon-off"></i> Salir', 'title="Salir del Sistema"') ?></li>
		</ul>
	</div>
</div>