<!-- Modal -->
<div id="ModalSoporte" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Solicitud de Soporte</h3>
    </div>
    <div class="modal-body">
        <form class="form-horizontal">
            <div class="alert oculto" id="alertSoporte"></div>
            <div class="control-group">
                <label class="control-label">Asunto :</label>
                <div class="controls">

                    <?php echo Form::text('titulo', 'class="span3 req"'); ?>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Descripción:</label>
                <div class="controls">

                    <?php echo Form::textarea('mensaje', 'class="span3 req"'); ?>

                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <i class="icon-spinner icon-spin icon-2x" id="espere" style="display:none;"></i>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <button class="btn btn-primary" id="btnSoporte">Enviar Solicitud</button>
    </div>
</div>

<script type="text/javascript">
$('#btnSoporte').on('click', function(e){
    e.preventDefault();
    $('#espere').toggle();
    $.post('<?php echo PUBLIC_PATH ?>ayudas/soporte/',
        {
            titulo: $('#titulo').val(),
            mensaje: $('#mensaje').val(),
            type:'json'
        },
        function(d){
            console.log(d.message);
            if (d.status=='success') {
                $('#alertSoporte').sucessMsj(d.message);
                $('#ModalSoporte').find('input[type=text]').val('').modal('hide');
                $('#espere').toggle();
            } else {
                $('#alertSoporte').errorMsj(d.message);
                $('#espere').toggle();
            }
        },
        'json'
    );
});
</script>

