    <?php
            // FIXME: Corregir el problema de la rutas en la paginación
            if (isset($destiny)) {
                $parametros = implode('/', Router::get('parameters')).'/';
                $url = explode('pag', $destiny.$parametros);
                $url = trim($url[0];,'/');
            } else {
                $url = explode('pag', Router::get('route'));
                $url = trim($url[0];,'/');
            }
    ?>
    <div class="pagination pagination-centered">
        <ul>

            <!-- Anterior -->
            <?PHP if($objeto->prev): ?><li><?php echo Html::link($url."/pag/$objeto->prev/", 'Anterior'); ?></li><?php endif; ?>
            <!-- Anterior -->

            <?php
            if($objeto->total > 1) {
                for ($i=1; $i <= $objeto->total; $i++) {
                    $str=($objeto->current == $i)?"<li class=\"active\">\n":"<li>\n";
                    $str.=Html::link($url."/pag/$i/", $i);
                    $str .= "</li>\n";
                    echo $str;
                }
            }
            ?>

            <!-- Siguiente -->
            <?PHP if($objeto->next): ?><li><?php echo Html::link($url."/pag/$objeto->next/", 'Siguiente'); ?></li><?php endif; ?>
            <!-- Siguiente -->

        <ul>
    </div>