        <?php if( $nivel <= 3 ): ?>
        <div class="control-group">
            <label class="control-label">Grupo:</label>
            <div class="controls">

                <?php
                if( $nivel < 3 && empty($distrito) ):
                    echo Form::select('adulto.grupos_id', array('Vacío'));
                else:
                    echo Form::dbSelect('adulto.grupos_id', 'nombre', array('grupos', 'listar',  $distrito));
                endif;
                ?>

            </div>
        </div>
        <script type="text/javascript">
            $('#adulto_grupos_id').on('change',function(e) {
                var id = $(this).val();
                if ( id ) {
                    $.getJSON(
                        '<?php echo PUBLIC_PATH,"ramas/listar/"; ?>'+id+'/',
                        {
                            type: 'json'
                        },
                        function(d){
                            if(d.status == 'success'){
                                var options = '<option value="0">No aplica</option>';
                                $(d.lista).each( function(i, e) {
                                    options += '<option value="' + e.id + '">' + e.nombre + '</option>';
                                });
                                $("#adulto_ramas_id").html(options);
                            }
                        }
                    );
                }
            });
        </script>
        <?php else: ?>
            <?php echo Form::hidden('adulto.grupos_id', null,  $grupo); ?>
        <?php endif; ?>

