<script type="text/javascript">
    $('form').on('submit', function(e) {
        e.preventDefault();
        $('#espere').toggle();
        var n = $('#nombre').val();
        var linkver = '<?php echo PUBLIC_PATH."estructura/2/"; ?>';
        var linkregion = '<?php echo PUBLIC_PATH."region/"; ?>';
        $.post(
            '<?php echo PUBLIC_PATH; ?>region/nueva',
            {
                type: 'json',
                registrar: 'e',
                nombre: n
            },
            function (d) {
                if (d.status=='success') {
                    $('#Msj').sucessMsj("Región creada exitosamente");
                    $('#vacio').remove();
                    var fila = '<tr>';
                    fila += '<td>&nbsp;</td>';
                    fila += '<td>'+n+'</td>';
                    fila += '<td class="text-center"> <a href="'+linkver+d.message+'" class="btn"><i class="icon-edit"></i> Detalle</a> </td>';
                    fila += '<td class="text-center"> <a href="#" class="btn btn-danger"><i class="icon-trash"></i> Borrar</a> </td>';
                    fila += '</tr>';
                    $('table>tbody').append(fila);
                    $('#ModalInsertar').modal('hide');
                    $('#ModalInsertar').find('input[type=text]').val('');
                    $('#espere').toggle();
                } else {
                    $('#alertPopup').errorMsj(d.message);
                    $('#espere').toggle();
                }
            },
            'json'
        );
    });
</script>