<script type="text/javascript">
    $('form').on('submit', function(e) {
        e.preventDefault();
        var n = $('#nombre').val();
        var linkver = '<?php echo PUBLIC_PATH."estructura/3/"; ?>';
        var linkregion = '<?php echo PUBLIC_PATH."distrito/"; ?>';
        $.post(
            '<?php echo PUBLIC_PATH; ?>distrito/nueva',
            {
                type: 'json',
                registrar: 'e',
                nombre: n,
                region_id: '<?php $p = Router::get("parameters"); echo $p[1]; ?>'
            },
            function (d) {
                if (d.status=='valid') {
                    $('#Msj').sucessMsj("Distrito creado exitosamente");
                    $('#vacio').remove();
                    var fila = '<tr>';
                    fila += '<td>&nbsp;</td>';
                    fila += '<td><a href="'+linkver+d.message+'">'+n+'</a></td>';
                    fila += '<td class="text-center"> <a href="'+linkregion+'desactivar/'+d.message+'" class="btn btn-warning"><i class="icon-frown"></i> Desactivar</a> </td>';
                    fila += '<td class="text-center"> <a href="#" class="btn btn-danger"><i class="icon-trash"></i> Borrar</a> </td>';
                    fila += '</tr>';
                    $('table>tbody').append(fila);
                    $('#ModalInsertar').modal('hide');
                } else {
                    $('#alertPopup').errorMsj(d.message);
                }
            },
            'json'
        );
    });
</script>