<div class="span8 offset2">
    <?php View::content(); ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th width="50%">Nombre</th>
                <th class="text-center">Créditos obtenidos de CVAL</th>
                <th class="text-center">Créditos obtenidos de CAC</th>
                <th class="text-center">Reporte Detallado</th>
            </tr>
        </thead>
        <tbody>
            <?php if(!count($lista)): ?>
            <tr id="vacio">
                <td colspan="5" class="text-center">No posee datos</td>
            </tr>
            <?php
                else:
                    foreach ($lista as $item):
                        $link = 'reportar/estructura/'.($nivel+1).'/'.$item->id;
                        $ahref = Html::link($link, $item->nombre);
            ?>
            <tr>
                <td>&nbsp;</td>
                <td width="50%"><?php echo  $ahref; ?></td>
                <td class="text-center"><?php echo ($item->cval)?$item->cval:0; ?></td>
                <td class="text-center"><?php echo ($item->cac)?$item->cac:0; ?></td>
                <td class="text-center"><?php echo "<a href='' class='btn btn-success'>Ver</a>"; ?></td>
            </tr>
            <?php
                    endforeach;
                endif;
            ?>
        </tbody>
    </table>
</div>