<div class="span8 offset2">
    <h3>Informe de Unidad</h3>
    <?php View::content(); ?>
</div>
<div class="span10 offset1">
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Nombre</th>
                <th class="text-center">Créditos CVAL</th>
                <th class="text-center">Créditos CAC</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($jovenes as $joven): ?>
            <tr>
                <td>&nbsp;</td>
                <td><?php echo $joven->nombre; ?></th>
                <td class="text-center"><?php echo $joven->cval; if($joven->cval>=135){' - Oro';} elseif($joven->cval>=85){' - Plata';} elseif($joven->cval>=40){' - Bronce';} ?></td>
                <td class="text-center"><?php echo $joven->cac; if($joven->cac>=135){echo ' - Oro';}elseif($joven->cac>=85){echo ' - Plata';}elseif($joven->cac>=40){echo ' - Bronce';} ?></td>
            </tr>
            <?php endforeach; ?>
        </thead>
        </tbody>
    </table>
</div>