<div class="span8 offset2">
        <?php
            $param = Router::get('parameters');
            $url = Router::get('controller').'/'.Router::get('action').'/'.$param[0].'/';
        ?>
        <ul class="pager">
            <?php if($ano == 2015): ?>
            <li class="previous">
                <?php echo Html::link($url.'2014', '&larr; 2013'); ?>
            </li>
            <?php else: ?>
            <li class="next">
                <?php echo Html::link($url, '2015 &rarr;'); ?>
            </li>
            <?php endif; ?>
        </ul>
    <h3>Informe de Unidad</h3>
    <?php View::content(); ?>
    <p>Créditos Generales <br/>
        CVAL: <?php echo Form::text('cval', 'class="span1" readonly="readonly"', $cval); ?>
        CAC: <?php echo Form::text('cac', 'class="span1" readonly="readonly"', $cac); ?>
    </p>
</div>
<div class="span10 offset1">
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Nombre</th>
                <th class="text-center">Créditos CVAL</th>
                <th class="text-center">Créditos CAC</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($jovenes as $joven): ?>
            <tr>
                <td>&nbsp;</td>
                <td><?php echo $joven['nombre']; ?></th>
                <td class="text-center">
                    <?php echo
                    ( ($joven['cval']>=100)?'<i class="icon-star" title="Obtenida"></i> ':'' )
                    . $joven['cval'] .
                    ( ($joven['cval']>=100)?' <i class="icon-star" title="Obtenida"></i>':'' );
                    ?>
                </td>
                <td class="text-center">
                    <?php echo
                    ( ($joven['cac']>=100)?'<i class="icon-star" title="Obtenida"></i> ':'' )
                    .  $joven['cac'] .
                    ( ($joven['cac']>=100)?' <i class="icon-star" title="Obtenida"></i>':'' );
                    ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </thead>
        </tbody>
    </table>
</div>