<div class="span8 offset2">
    <h3>Informe de Unidad</h3>
    <?php View::content(); ?>
</div>
<div class="span10 offset1">
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Nombre</th>
                <th class="text-center">Créditos CVAL</th>
                <th class="text-center">Créditos CAC</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($jovenes as $joven): ?>
            <tr>
                <td>&nbsp;</td>
                <td><?php echo $joven['nombre']; ?></th>
                <td class="text-center">
                    <?php echo
                    ( ($joven['cval']>=100)?'<i class="icon-star" title="Obtenida"></i> ':'' )
                    . $joven['cval'] .
                    ( ($joven['cval']>=100)?' <i class="icon-star" title="Obtenida"></i>':'' );
                    ?>
                </td>
                <td class="text-center">
                    <?php echo
                    ( ($joven['cac']>=100)?'<i class="icon-star" title="Obtenida"></i> ':'' )
                    .  $joven['cac'] .
                    ( ($joven['cac']>=100)?' <i class="icon-star" title="Obtenida"></i>':'' );
                    ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </thead>
        </tbody>
    </table>
</div>