<div class="span8 offset2">
    <h3>Generar Informes Generales</h3>
    <h4 class="visible-print"></h4>
    <?php View::content(); ?>
</div>
<div class="span4 offset4 hidden-print">
        <?php print Session::get('region_id'); View::partial('adultos/region', null, array('nivel'=>$nivel, 'region'=>Session::get('region_id'))); ?>

        <?php $estructura = ($nivel < 2)?null:$estructura; View::partial('adultos/distrito', null, array('nivel'=>$nivel, 'region'=>$estructura, 'distrito'=>Session::get('distrito_id'))); ?>

        <?php $estructura = ($nivel < 3)?null:$estructura; View::partial('adultos/grupos', null, array('nivel'=>$nivel, 'distrito'=>$estructura, 'grupo'=>Session::get('grupos_id'))); ?>

        <button class="btn btn-primary" id="btnGenerar">Generar</button>
        <a href="#" onClick="print();" class="btn btn-success disabled" id="btnImprimir">Imprimir</a>
        <br/>
        <br/>
</div>
<div class="span10 offset1 hidden-print">
    <p class="text-center">
    <em class="text-center"><b>Importante: </b>Región, distrito, grupo o unidad de no aparecer en este reporte es por la total ausencía de actividades reportadas</em>
</p>
</div>
<div class="clearfix"></div>
<div class="span10 offset1">
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Nombre</th>
                <th class="text-center">Insignias CVAL</th>
                <th class="text-center">Insignias CAC</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="8">&nbsp;</td>
            </tr>
        </thead>
        </tbody>
    </table>
</div>
<?php echo Tag::js('form'); ?>
<script type="text/javascript">
    $('#btnGenerar').on('click', function(e){
        e.preventDefault();
        $('table>tbody').html('<tr><td colspan="8"d class="text-center"><i class="icon-spinner icon-spin"></i> Generando, por favor espere...</td></tr>');
        var region = $('#adulto_region_id').val(),region_nombre = $('#adulto_region_id option:selected').text();
        var distrito = $('#adulto_distrito_id').val(),distrito_nombre = $('#adulto_distrito_id option:selected').text();
        var grupo = $('#adulto_grupos_id').val(),grupo_nombre = $('#adulto_grupos_id option:selected').text();
        var url='',nombre='',str='';
        var orden=0,cval=0,cac=0;
        var titulo = 'Nacional';
        var detalle = '';
        if (region != undefined && region != 0) {
            url += region+'/';
            titulo = region_nombre;
            detalle = '';
        }
        if (distrito != undefined && distrito != 0 && distrito != 'Vacío') {
            url += distrito+'/';
            titulo = region_nombre+' > '+distrito_nombre;
            detalle = '';
        }
        if (grupo != undefined && grupo != 0 && grupo != 'Vacío') {
            url += grupo+'/';
            titulo = region_nombre+' > '+distrito_nombre+' > '+grupo_nombre;
            detalle = '<a href="<?php echo PUBLIC_PATH; ?>reportar/informe_unidad/{num}/">Detalles</a>';
        }
        $('h4').html(titulo);
        $.post(
            '<?php echo PUBLIC_PATH; ?>reportar/consulta/'+url,
            {
                type: 'json'
            },
            function(d){
                if (d.status == 'valid') {
                    $('table>tbody').html('');
                    $.each(d.jovenes, function(index, item) {
                        if(orden==0){
                            orden=item.campo;
                            nombre = item.campo_nombre;
                        } else if( orden!=0 && item.campo != orden) {
                            d = detalle.replace('{num}', orden);
                            str='<tr><td>&nbsp;</td><td>'+nombre+' '+d+'</td>';
                            str+='<td class="text-center">'+cval+'</td>';
                            str+='<td class="text-center">'+cac+'</td>';
                            $('table>tbody').append(str);
                            orden=item.campo,nombre=item.campo_nombre,cval=0,cac=0;
                        }
                        if(item.cval>=100){
                            cval+=1;
                        }
                        if(item.cac>=100){
                            cac+=1;
                        }
                    });
                    // if( cval != 0 || cac != 0 ) {
                        d = detalle.replace('{num}', orden);
                        str='<tr><td>&nbsp;</td><td>'+nombre+' '+d+'</td>';
                        str+='<td class="text-center">'+cval+'</td>';
                        str+='<td class="text-center">'+cac+'</td>';
                        $('table>tbody').append(str);
                    // }
                    $('#btnImprimir').removeClass('disabled');
                } else {
                    $('table>tbody').html('<tr><td colspan="8" class="text-center">Informe Vacío</td></tr>');
                }
            },
            'json'
        );
    });
</script>