    <?php View::content(); ?>
    <div class="span12">
        <div class="row">
            <div class="span10 offset1 cajas">
                <h5>Información</h5>
                <div class="cajitas">
                    <table class="table table-striped table-actividades">
                        <thead>
                            <tr>
                                <th class="th-fecha">Fecha</th>
                                <th>Actividades</th>
                                <th class="text-center">Créditos</th>
                                <th class="text-center">Reportados</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($objeto as $dia): ?>
                            <tr>
                                    <td><?php echo $dia->fecha ?></td>
                                    <td><?php echo $dia->nombre; ?></td>
                                    <td class="text-center"><?php echo $dia->creditos; ?></td>
                                    <td class="text-center"><?php echo ($dia->reportado)?'<i class="icon-check"></i>':'<i class="icon-check-empty"></i>'; ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <p>Créditos Mensuales <br/> CVAL: <?php echo Form::text('cval', 'class="span1" readonly="readonly"'); ?> CAC: <?php echo Form::text('cac', 'class="span1" readonly="readonly"'); ?></p>
                <?php echo Form::open(); ?>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Credencial</th>
                            <th>Jóven</th>
                            <!-- Actividades -->
                            <?php foreach ($objeto as $dia): ?>
                            <th class="text-center"><?php echo ($dia->cval == 1)?'CVAL':'CAC'; ?><br/><?php echo $dia->fecha ?></th>
                            <?php endforeach; ?>
                            <!-- Actividades -->
                            <th class="text-center">CVAL</th>
                            <th class="text-center">CAC</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($jovenes as $id => $item): ?>
                        <tr>
                            <td><?php echo $item['credencial']; ?></td>
                            <td><?php echo $item['nombre']; ?></td>
                            <?php
                            $cval = 0;
                            $cac = 0;
                            foreach ($item['actividades'] as $dia):
                                $tipo = ($dia['cval']==1)?'cval':'cac';
                                if ($dia['viejo'] == 1){
                                    $check = True;
                                    if($dia['cval']==1){$cval+=$dia['creditos'];} else {$cac+=$dia['creditos'];}
                                } else{ $check = False; }
                                $disabled = ($dia['viejo'] != 0)?"disabled='disabled'":"";
                            ?>
                            <td class="text-center">
                                <?php echo Registro::check("campo[$id][]", $dia['id'], "data-creditos='".$dia['creditos']."' data-tipo='$tipo' data-id='$id' $disabled",$check); ?>
                            </td>
                            <?php endforeach; ?>
                            <td class="text-center"><?php echo Registro::number('cval['.$id.']', 'class="span1" readonly="readonly"', $cval); ?></td>
                            <td class="text-center"><?php echo Registro::number('cac['.$id.']', 'class="span1" readonly="readonly"', $cac); ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <button type="submit" class="btn btn-success pull-right" name="registrar"><i class="icon-cogs"></i> Registrar</button>
                <?php echo Form::close(); ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var factor = <?php echo $rama; ?>;
        function calcularCreditos() {
            var data = this.id.split('_');
            var tipo = $(this).attr('data-tipo');
            var valor = 0;
            var mensual = 0;
            // Calculo de Créditos Individuales
            $('form').find('#campo_'+data[1]+'_[data-tipo="'+tipo+'"]:checked').each(function(){
                valor += parseInt($(this).attr('data-creditos'));
            });
            $('#'+tipo+'_'+data[1]).val(valor);

            // Calculo de Créditos de la Unidad
            $('form').find('input[data-tipo="'+tipo+'"]:checked').each(function(){
                mensual += parseInt( $(this).attr('data-creditos'));
            });
            $('#'+tipo).val(Math.round(mensual/factor));
        }

        // FIXME: Debo corregir esto con más tiempo y con una solución más elegante
        $('input').on('click', calcularCreditos);
    </script>