    <?php View::content(); ?>
    <div class="span12">
        <div class="row">
            <div class="span10 offset1 cajas">
                <h5>Información</h5>
                <div class="cajitas">
                    <table class="table table-striped table-actividades">
                        <thead>
                            <tr>
                                <th class="th-fecha">Fecha</th>
                                <th>Actividades</th>
                                <th class="text-center">Créditos</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($objeto as $dia): ?>
                            <tr>
                                    <?php if ($dia->fecha{4} == '-') : ?>
                                    <td><?php $fecha = explode('-', $dia->fecha); echo $fecha[2],'/',$fecha[1],'/',$fecha[0]; ?></td>
                                    <td><?php echo $dia->nombre; ?></td>
                                    <td class="text-center"><?php echo (($dia->duracion*$dia->bcp)+$dia->ba+$dia->bgi); ?></td>
                                    <?php endif; ?>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <p>Créditos Mensuales <br/> CVAL: <?php echo Form::text('cval', 'class="span1" readonly="readonly"'); ?> CAC: <?php echo Form::text('cac', 'class="span1" readonly="readonly"'); ?></p>
                <?php echo Form::open(); ?>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Credencial</th>
                            <th>Jóven</th>
                            <!-- Actividades -->
                            <?php foreach ($objeto as $dia): ?>
                            <th class="text-center"><?php echo ($dia->cval == 1)?'CVAL':'CAC'; ?><br/><?php echo $dia->fecha ?></th>
                            <?php endforeach; ?>
                            <!-- Actividades -->
                            <th class="text-center">CVAL</th>
                            <th class="text-center">CAC</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($jovenes as $item): ?>
                        <tr>
                            <td><?php echo $item->credencial; ?></td>
                            <td><?php echo trim($item->primer_nombre.' '.$item->segundo_nombre)." ".trim($item->primer_apellido.' '.$item->segundo_apellido); ?></td>
                            <?php
                            foreach ($objeto as $dia):
                                $creditos = ($dia->duracion*$dia->bcp)+$dia->ba+$dia->bgi;
                                $tipo = ($dia->cval==1)?'cval':'cac';
                            ?>
                            <td class="text-center"><?php echo Registro::check("campo[$item->id][]", $dia->id, "data-creditos='$creditos' data-tipo='$tipo' data-id='$item->id'"); ?></td>
                            <?php endforeach; ?>
                            <td class="text-center"><?php echo Registro::number('cval['.$item->id.']', 'class="span1" readonly="readonly"'); ?></td>
                            <td class="text-center"><?php echo Registro::number('cac['.$item->id.']', 'class="span1" readonly="readonly"'); ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <button type="submit" class="btn btn-success pull-right" name="registrar"><i class="icon-cogs"></i> Registrar</button>
                <?php echo Form::close(); ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var factor = <?php echo $rama; ?>;
        function calcularCreditos() {
            var data = this.id.split('_');
            var tipo = $(this).attr('data-tipo');
            var valor = 0;
            var mensual = 0;
            // Calculo de Créditos Individuales
            $('form').find('#campo_'+data[1]+'_[data-tipo="'+tipo+'"]:checked').each(function(){
                valor += parseInt($(this).attr('data-creditos'));
            });
            $('#'+tipo+'_'+data[1]).val(valor);

            // Calculo de Créditos de la Unidad
            $('form').find('input[data-tipo="'+tipo+'"]:checked').each(function(){
                mensual += parseInt( $(this).attr('data-creditos'));
            });
            $('#'+tipo).val(Math.round(mensual/factor));
        }

        // FIXME: Debo corregir esto con más tiempo y con una solución más elegante
        $('input').on('click', calcularCreditos);
    </script>