    <?php View::content(); ?>
    <div class="span12">
        <div class="row">
        <?php if($ano_actual == 2016):
        $param = Router::get('parameters');
        $url = Router::get('controller').'/'.Router::get('action').'/'.$param[0].'/';
        ?>
        <ul class="pager">
            <?php if($ano == 2016): ?>
            <li class="previous">
                <?php echo Html::link($url.'2015', '&larr; 2015'); ?>
            </li>
            <?php else: ?>
            <li class="next">
                <?php echo Html::link($url, '2016 &rarr;'); ?>
            </li>
            <?php endif; ?>
        </ul>
        <?php endif; ?>
        <?php $i=1; foreach ($objeto as $mes => $dias): $cantidad = count($dias)?>
            <div class="span4 cajas">
                <h5>
                    <?php
                    // A partir del 2014 solo se podrá reportar los 3 últimos meses en curso
                    // if ( $ano == 2014 && $ano_actual == 2015 && $mes_actual == 1 && $cantidad != 0) {
                    //     $mes .= ' <small>' . Html::link("reportar/nuevo/$id/$i/".($ano_actual-1),'Reportar').'</small>';
                    // } elseif ( $ano_actual >= 2015 && $cantidad != 0 && ( ($mes_actual-2) <= $i  && $mes_actual >= $i ) ) {
                    //     $mes .= ' <small>' . Html::link("reportar/nuevo/$id/$i/",'Reportar').'</small>';
                    // }
                    // $mes .= ' <small>' . Html::link("reportar/nuevo/$id/$i/".$ano,'Reportar').'</small>';
                    if ( $cantidad != 0 ) {
                        $mes .= ' <small>' . Html::link("reportar/nuevo/$id/$i/".$ano,'Reportar').'</small>';
                    }
                    echo $mes;
                    ?>
                </h5>
                <div class="cajitas">
                    <table class="table table-striped table-actividades">
                            <thead>
                                <tr>
                                    <th class="th-fecha text-center">Fecha</th>
                                    <th class="text-center">Actividades</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if ($cantidad != 0): foreach ($dias as $dia): ?>
                                <tr>
                                        <?php if ($dia->fecha{4} == '-') : ?>
                                        <td><?php $fecha = explode('-', $dia->fecha); echo $fecha[2],'/',$fecha[1],'/',$fecha[0]; ?></td>
                                        <td><?php echo $dia->nombre; ?></td>
                                        <?php endif; ?>
                                </tr>
                                <?php endforeach; else: ?>
                                <tr>
                                    <td colspan="2" class="text-center">Vacío</td>
                                </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                </div>
            </div>
        <?php if ( ($i%3)==0 ): ?>
        </div>
        <div class="row">
        <?php endif; $i++;  ?>
    <?php endforeach; ?>