    <?php View::content(); ?>
    <div class="span12">
        <div class="row">
        <?php $i=1; foreach ($objeto as $mes => $dias): $cantidad = count($dias)?>
            <div class="span4 cajas">
                <h5>
                    <?php echo $mes,' ',($cantidad != 0 && $mes_actual-2 <= $i  && $mes_actual >= $i )?'<small>'.Html::link('reportar/nuevo/'.$id.'/'.$i,'Reportar').'</small>':''; ?>
                </h5>
                <div class="cajitas">
                    <table class="table table-striped table-actividades">
                            <thead>
                                <tr>
                                    <th class="th-fecha text-center">Fecha</th>
                                    <th class="text-center">Actividades</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if ($cantidad != 0): foreach ($dias as $dia): ?>
                                <tr>
                                        <?php if ($dia->fecha{4} == '-') : ?>
                                        <td><?php $fecha = explode('-', $dia->fecha); echo $fecha[2],'/',$fecha[1],'/',$fecha[0]; ?></td>
                                        <td><?php echo $dia->nombre; ?></td>
                                        <?php endif; ?>
                                </tr>
                                <?php endforeach; else: ?>
                                <tr>
                                    <td colspan="2" class="text-center">Vacío</td>
                                </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                </div>
            </div>
        <?php if ( ($i%3)==0 ): ?>
        </div>
        <div class="row">
        <?php endif; $i++;  ?>
    <?php endforeach; ?>