<?php Tag::css('ayudas'); ?>
<div class="span12">
    <h3 id="inicio">¿Qué son?</h3>
    <p>Los concursos nacionales son un instrumento de certificación de la vida de grupo que lleva el joven en la unidad.</p>

    <p>Mediante esta herramienta se puede apreciar la progresión de él, teniendo una vida de grupo rica en experiencias propias que brinda su marco simbólico, además los Concursos Nacionales contribuyen en la orientación de dos aspectos significativos, la Conciencia Ecológica e Identidad Nacional.</p>
</div>
<div class="span6">
    <blockquote>
        <h5>Concursos de Vida al Aire Libre - CVAL</h5>
        <p>Esta enmarcado en el escenario mínimo necesario, para contribuir al desarrollo integral del joven durante su permanencia en la unidad.</p>

        <p>Se consideran las actividades que se efectúan en cada unidad y etapa de progresión, así como otras que le sean complementarias para su interacción con el medio ambiente.</p>
    </blockquote>
</div>
<div class="span6">
    <blockquote>
        <h5>Concurso de Acción Comunitaria – CAC</h5>
        <p>Busca incentivar y medir la interacción de los Grupos Scouts con sus comunidades, favoreciendo así al propósito del movimiento en la educación de los jóvenes para que desempeñen un papel activo en la sociedad, tomando en consideración la vida de grupo que los niños, adolescentes y jóvenes llevan en las unidades.</p>
    </blockquote>
</div>
<div class="span12">
    <h3>Elementos a considerar para el reporte de las actividades</h3>
    <ul>
        <li><a href="#conceptos">Conceptos Programáticos (CP)</a></li>
        <li><a href="#asistencia">Bonos de asistencia (BA)</a></li>
        <li><a href="#indepencia">Grado de independencia (GI)</a></li>
        <li><a href="#mecanismo">Mecanismos operacionales</a></li>
    </ul>
</div>

<div class="span12">
    <h3 id="conceptos">Conceptos Programáticos - CP</h3>
    <p>
        Son las características que identifican una actividad scout de otra, considerando el alcance de los objetivos educativos que persigan.<br>
        A continuación podrás apreciar un listado de actividades, que según la unidad, podrán acreditarse en los concursos nacionales.
    </p>
    <div class="row">
        <div class="span6">
            <b>Criterios para el Concurso de Vida al Aire Libre (CVAL)</b>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Actividades</th>
                        <th class="text-center">Manada</th>
                        <th class="text-center">Tropa</th>
                        <th class="text-center">Clan</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td class="text-center"> Parques Recreacionales<br><small>(Visitas o paseos sin pernocta)</small> </td>
                        <td class="text-center manada">1</td>
                        <td class="text-center tropa">1</td>
                        <td class="text-center clan">1</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Parques Nacionales y Naturales<br><small>(Visita o acampada)</small> </td>
                        <td class="text-center manada">3</td>
                        <td class="text-center tropa">3</td>
                        <td class="text-center clan">3</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Monumentos naturales<br><small>(Visita o acampada)</small> </td>
                        <td class="text-center manada">3</td>
                        <td class="text-center tropa">3</td>
                        <td class="text-center clan">3</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Excursión de un día </td>
                        <td class="text-center manada">1</td>
                        <td class="text-center tropa">1</td>
                        <td class="text-center clan">1</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Noche de lobos, Noche Rover, o excursión con pernocta<br><small>(Créditos x Noche)</small> </td>
                        <td class="text-center manada">3</td>
                        <td class="text-center tropa">3</td>
                        <td class="text-center clan">3</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Acantonamiento, campamento o peregrinaje<br><small>(Créditos x Noche)</small> </td>
                        <td class="text-center manada">5</td>
                        <td class="text-center tropa">5</td>
                        <td class="text-center clan">5</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Ciclos Institucionales de Programa - VAL<br><small>(Tu Rastro, Paxtu, Cadipas, Carepas, Canapas, Ruta Rover, Moots / Créditos x Noche)</small> </td>
                        <td class="text-center manada">2</td>
                        <td class="text-center tropa">2</td>
                        <td class="text-center clan">2</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span6">
            <b>Criterios para el Concurso de Acción Comunitaria (CAC)</b>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Actividades</th>
                        <th class="text-center">Manada</th>
                        <th class="text-center">Tropa</th>
                        <th class="text-center">Clan</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td class="text-center"> Limpieza de áreas públicas y verdes<br><small>(Parques, playas u otros)</small> </td>
                        <td class="text-center manada">1</td>
                        <td class="text-center tropa">1</td>
                        <td class="text-center clan">1</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Campañas sobre ciudadanía </td>
                        <td class="text-center manada">1</td>
                        <td class="text-center tropa">1</td>
                        <td class="text-center clan">1</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Proyectos Medioambientales<br><small>(Reforestaciones, recuperación de áreas verdes, campañas ecológicas, servicios u otros similares)</small> </td>
                        <td class="text-center manada">3</td>
                        <td class="text-center tropa">3</td>
                        <td class="text-center clan">3</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Actividades curriculares<br><small>(Labor social o servicio comunitario en coordinación con la institución educativa)</small> </td>
                        <td class="text-center manada">3</td>
                        <td class="text-center tropa">3</td>
                        <td class="text-center clan">3</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Desarrollo de actividades basadas en las Metas del Milenio </td>
                        <td class="text-center manada">5</td>
                        <td class="text-center tropa">5</td>
                        <td class="text-center clan">5</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Desarrollo con la comunidad<br><small>(Actividades previamente planificada con otros entes, tales como: Servicios, buenas acciones, convenios, LIS u otros similares)</small> </td>
                        <td class="text-center manada">3</td>
                        <td class="text-center tropa">3</td>
                        <td class="text-center clan">3</td>
                    </tr>
                    <tr>
                        <td class="text-center"> Ciclos Institucionales de Programa  - CAC<br><small>(Día Mundial de las Playas, 100.000 Horas, Día del Agua, Acción Rover, Toma Rover u otros similares)</small> </td>
                        <td class="text-center manada">2</td>
                        <td class="text-center tropa">2</td>
                        <td class="text-center clan">2</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="span12">
    <h3 id="asistencia">Bonos de Asistencias - BA</h3>
    <p>
        Los bonos de asistencia están determinados por la cantidad de jóvenes aistentes a la actividad, calculados bajo la membresía ideal de la unidad, por lo que corresponden en igualdad de valores para cada una.
    </p>
    <div class="span8 offset2">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-center">Criterios</th>
                    <th class="text-center">Bono</th>
                    <th class="text-center">Manada</th>
                    <th class="text-center">Tropa</th>
                    <th class="text-center">Clan</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td class="text-center"> 25% de la membresía ideal </td>
                    <td class="text-center"><b>2</b></td>
                    <td class="text-center manada">1 a 6</td>
                    <td class="text-center tropa">1 a 8</td>
                    <td class="text-center clan">1 a 3</td>
                </tr>
                <tr>
                    <td class="text-center"> 50% de la membresía ideal </td>
                    <td class="text-center"><b>4</b></td>
                    <td class="text-center manada">7 a 12</td>
                    <td class="text-center tropa">9 a 16</td>
                    <td class="text-center clan">4 a 6</td>
                </tr>
                <tr>
                    <td class="text-center"> 75% de la membresía ideal </td>
                    <td class="text-center"><b>6</b></td>
                    <td class="text-center manada">13 a 18</td>
                    <td class="text-center tropa">17 a 24</td>
                    <td class="text-center clan">7 a 9</td>
                </tr>
                <tr>
                    <td class="text-center"> 100% de la membresía ideal </td>
                    <td class="text-center"><b>8</b></td>
                    <td class="text-center manada">Más de 19</td>
                    <td class="text-center tropa">Más de 25</td>
                    <td class="text-center clan">Más de 10</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="span12">
    <h3 id="independencia">Grado de Independencia - GI</h3>
    <p>
        Corresponde al nivel que desarrolle la actividad, mientras más autonomía y participación juvenil halla, más créditos tendrá la actividad.
    </p>
    <div class="span8 offset2">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-center">Criterios</th>
                    <th class="text-center">Manada</th>
                    <th class="text-center">Tropa</th>
                    <th class="text-center">Clan</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td class="text-center"> Pequeños grupos (Patrullas o Equipos Rover) </td>
                    <td class="text-center manada">N/A</td>
                    <td class="text-center tropa">5</td>
                    <td class="text-center clan">5</td>
                </tr>
                <tr>
                    <td class="text-center"> Unidad (Manada, Tropa o Clan) </td>
                    <td class="text-center manada">5</td>
                    <td class="text-center tropa">3</td>
                    <td class="text-center clan">3</td>
                </tr>
                <tr>
                    <td class="text-center"> Dos o más unidades en conjunto (Grupo, Integrupos y/o Distrito) </td>
                    <td class="text-center manada">2</td>
                    <td class="text-center tropa">2</td>
                    <td class="text-center clan">2</td>
                </tr>
                <tr>
                    <td class="text-center"> Nivel Nacional y/o Región </td>
                    <td class="text-center manada">1</td>
                    <td class="text-center tropa">1</td>
                    <td class="text-center clan">1</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="span12">
    <h3 id="mecanismo">Mecanismos Operacionales</h3>
    <p>
        <b>Líder del Equipo</b><br>
        Será un miembro de la unidad encargado de ingresas al Sistema de reporte, y de informar al Motivador de los avances de la unidad.
    </p>
    <div class="alert alert-info"> <i class="icon-info icon-2x"></i> En esta etapa de implementación de Sistema en línea, deberá ser un adulto scout. </div>
    <p>
        <b>Dinámica</b><br>
        A continuación se describe la dinámica de participación para los Concursos Nacionales.
        <ol>
            <li>Después de la realización de cada actividad, el líder registra y reporta esta en el <b>Sistema en línea</b>. Teniendo sumo cuidado de introducir correctamente los datos, y llevar verázmente la asistencia, para que se de el cáculo correcto de los créditos correspondientes.</li>
            <li>El sistema calcula la puntuación de cada actividad registrada y pone la información a disposición de las autoridades correspondientes.</li>
            <li>De existir algún error en el sistema, el Líder deberá reportarlo de inmediato, para hacer los ajustes necesarios y mantener la valides de la información.</li>
            <li>Una vez alcanzada la acreditación mínima 100 créditos para cada concurso, podrán adquirir las insignias en el Centro de Servicio Scout Nacional con la hoja reporte correspondiente.  Las insignias estarán disponible después del segundo semestres del año.</li>
        </ol>
    </p>
</div>

<a href="#trademark"><div class="subir"> <i class="icon-chevron-up icon-3x"></i></div></a>

<script type="text/javascript">
    var subir = $('.subir');
    subir.fadeOut();
    $(window).scroll(function () {
        if ($(window).scrollTop() > 300) {
            subir.fadeIn();
        } else {
            subir.fadeOut();
        }
    });
</script>