<?php Tag::css('videos'); ?>
<script src="//www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">
    google.load("swfobject", "2.1");
</script>
<div class="span12">
    <div class="row">
        <?php $i=0;foreach ($items as $item): ?>

        <div class="span4">
            <article>
                <header><?php echo $item['title'] ?></header>
                <img src="<?php echo $item['image'] ?>">
                <a href="#viewer" class="ver" data-toggle="modal" data-video="<?php echo $item['id'] ?>">Ver vídeo</a>
            </article>
        </div>

        <?php $i++; if ($i == count($items)): ?>
    </div> <!-- End Row -->
        <?php elseif (($i%3) == 0): ?>
    </div> <!-- End Row -->

    <div class="row">
        <?php endif;?>

        <?php endforeach; ?>
</div>
<?php View::partial('modal_video'); ?>