<div class="span10 offset1">
    <h3>Unidad <?php $cantidad = count($lista); echo ($cantidad)?$lista[0]->nombre:''; ?></h3>
    <div class="alert" id="Msj"></div>
    <?php View::content(); ?>
    <a href="#ModalInsertar" role="button" data-toggle="modal" class="btn btn-success pull-right"><i class="icon-plus"></i> Agregar Joven</a>
    <table class="table table-striped sorted">
        <thead>
            <tr>
                <th>Credencial</th>
                <th>Nombre</th>
                <th>Equipo</th>
                <th colspan="3" class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
            <?php
            
            if(!$cantidad): ?>
            <tr>
                <td colspan="7" class="text-center" id="vacio">No posee Jóvenes</td>
            </tr>
            <?php
                else:
                    foreach ($lista as $item):
            ?>
            <tr>
                <td><?php echo $item->credencial; ?></td>
                <td><?php echo trim($item->primer_nombre.' '.$item->segundo_nombre)." ".trim($item->primer_apellido.' '.$item->segundo_apellido); ?></td>
                <td></td>
                <td class="text-center">
                    <?php if (True): ?>
                        <a href="#" class="btn btn-warning"><i class="icon-frown"></i> Inactivar</a>
                    <?php else: ?>
                        <a href="#" class="btn btn-success"><i class="icon-smile"></i> Activar</td></a>
                    <?php endif; ?>
                <td class="text-center"> <a href="#" class="btn btn-primary"><i class="icon-edit"></i> Editar</a> </td>
                <td class="text-center"> <a href="#" class="btn btn-danger"><i class="icon-trash"></i> Borrar</a> </td>
            </tr>
            <?php
                    endforeach;
                endif;
            ?>
        </tbody>
    </table>
</div>
<!-- Modal -->
<div id="ModalInsertar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Registrar Jóven</h3>
    </div>
    <div class="modal-body">
        <form class="form-horizontal">
            <div class="alert" id="alertPopup"></div>
            <div class="control-group">
                <label class="control-label">Cédula:</label>
                <div class="controls">

                    <?php echo Registro::cmbNac('nac', 'class="span1"'); ?> <?php echo Registro::number('cedula', 'class="span2"'); ?>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Credencial:</label>
                <div class="controls">

                    <?php echo Registro::number('credencial', 'class="span2"'); ?>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Primer Nombre:</label>
                <div class="controls">

                	<?php echo Form::text('primer_nombre', 'class="span2 req"'); ?>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Segundo Nombre:</label>
                <div class="controls">

                    <?php echo Form::text('segundo_nombre', 'class="span2"'); ?>

                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Primer Apellido:</label>
                <div class="controls">

                    <?php echo Form::text('primer_apellido', 'class="span2 req"'); ?>

                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Segundo Apellido:</label>
                <div class="controls">

                    <?php echo Form::text('segundo_apellido', 'class="span2"'). Form::hidden('ramas_id', null, $rama); ?>

                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <i class="icon-spinner icon-spin icon-2x" id="espere"></i>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <button class="btn btn-primary" id="btnRegistrar">Registrar</button>
    </div>
</div>
<?php echo Tag::js('form'); ?>
<script type="text/javascript">
    $('.alert').fadeOut();

    function spinnerRegistro() {
        ($('#espere').css('display')=='none')? $('#espere').css('display', 'inline-block') : $('#espere').css('display', 'none') ;
    }

    $('#btnRegistrar').on('click', function(evento) {
        evento.preventDefault();
        spinnerRegistro();
        var credencial = $('#credencial').val(), primer_nombre = $('#primer_nombre').val(), segundo_nombre = $('#segundo_nombre').val(), primer_apellido = $('#primer_apellido').val(), segundo_apellido = $('#segundo_apellido').val();
        $.post(
            '<?php echo PUBLIC_PATH; ?>jovenes/registrar/',
            {
                type: 'json',
                "registro[nacionalidad]": $('#nac').val(),
                "registro[cedula]": $('#cedula').val(),
                "registro[credencial]": credencial,
                "registro[primer_nombre]": primer_nombre,
                "registro[segundo_nombre]": segundo_nombre,
                "registro[primer_apellido]": primer_apellido,
                "registro[segundo_apellido]": segundo_apellido,
                "registro[ramas_id]": $('#ramas_id').val(),
                registrar: 'registrando'
            },
            function(data) {
                spinnerRegistro();
                if (data.status == "success") {
                    $('#Msj').sucessMsj(data.message);
                    $('#vacio').remove();
                    var joven = '<tr>';
                    joven += '<td>'+credencial+'</td>';
                    joven += '<td>'+primer_nombre+' '+segundo_nombre+' '+primer_apellido+' '+segundo_apellido+'</td>';
                    joven += '<td></td>';
                    joven += '<td class="text-center">';
                    joven += '<a href="#" class="btn btn-warning"><i class="icon-frown"></i> Inactivar</a>';
                    joven += '<td class="text-center"> <a href="#" class="btn btn-primary"><i class="icon-edit"></i> Editar</a> </td>';
                    joven += '<td class="text-center"> <a href="#" class="btn btn-danger"><i class="icon-trash"></i> Borrar</a> </td>';
                    joven += '</tr>';
                    $('table>tbody').append(joven);
                    $('#ModalInsertar').modal('hide');
                } else {
                    $('#alertPopup').errorMsj(data.message);
                    // $('#ModalInsertar').modal('hide');
                }
            },
            'json'
        ).error(function() {
            spinnerRegistro();
            $('#Msj').errorMsj('Ha occurrido un error inesperado, actualice la página y vuelva a intentar');
            $('#ModalInsertar').modal('hide');
        });
    });
</script>