<div class="span10 offset1">
	<?php View::content(); ?>
	<a href="#myModal" role="button" data-toggle="modal" class="btn btn-success pull-right"><i class="icon-plus"></i> Agregar Joven</a>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>ID</th>
				<th>Credencial</th>
				<th>Nombre</th>
				<th>Equipo</th>
				<th colspan="3">Opciones</th>
			</tr>
		</thead>
		<tbody>
			<?php for($i=1;$i<=20;$i++):	?>
			<tr>
				<td><?php echo $i; ?></td>
				<td>123456789</td>
				<td>Jaro Andrei Marval Pereira</td>
				<td></td>
				<td>Inactivar</td>
				<td>Editar</td>
				<td>Borrar</td>
			</tr>
			<?php endfor; ?>
		</tbody>
	</table>
</div>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
<p>One fine body…</p>
</div>
<div class="modal-footer">
<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
<button class="btn btn-primary">Save changes</button>
</div>
</div>