<div class="span10 offset1">
    <h3>Unidad <?php $cantidad = count($lista); echo ($cantidad)?$lista[0]->nombre:''; ?></h3>
    <div class="alert oculto" id="Msj"></div>
    <?php View::content(); ?>
    <a href="#ModalInsertar" role="button" data-toggle="modal" class="btn btn-success pull-right"><i class="icon-plus"></i> Agregar Joven</a>
    <table class="table table-striped sorted">
        <thead>
            <tr>
                <th>Credencial</th>
                <th>Nombre</th>
                <th <?php if($registro): ?>colspan="2"<?php endif; ?> class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
            <?php
            
            if(!$cantidad): ?>
            <tr>
                <td colspan="7" class="text-center" id="vacio">No posee Jóvenes</td>
            </tr>
            <?php
                else:
                    foreach ($lista as $item):
                        $nombre = trim($item->primer_nombre.' '.$item->segundo_nombre)." ".trim($item->primer_apellido.' '.$item->segundo_apellido);
            ?>
            <tr>
                <td><?php echo $item->credencial; ?></td>
                <td><?php echo $nombre; ?></td>
                <td class="text-center"> <a href="#" class="btn btn-primary editar"><i class="icon-edit"></i> Editar</a> </td>
                <?php if($registro): ?><td class="text-center"> <a href="#" class="btn btn-danger" data-id="<?php echo $item->id; ?>" data-nombre="<?php echo $nombre; ?>"><i class="icon-trash"></i> Borrar</a> </td><?php endif; ?>
            </tr>
            <?php
                    endforeach;
                endif;
            ?>
        </tbody>
    </table>
</div>
<!-- Modal -->
<div id="ModalInsertar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Registrar Jóven</h3>
    </div>
    <div class="modal-body">
        <form class="form-horizontal">
            <div class="alert oculto" id="alertPopup"></div>
            <div class="control-group">
                <label class="control-label">Cédula:</label>
                <div class="controls">

                    <?php echo Registro::cmbNac('nac', 'class="span1"'); ?> <?php echo Registro::number('cedula', 'class="span2"'); ?>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Credencial:</label>
                <div class="controls">

                    <?php echo Registro::number('credencial', 'class="span2"'); ?>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Primer Nombre:</label>
                <div class="controls">

                	<?php echo Form::text('primer_nombre', 'class="span2 req"'); ?>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Segundo Nombre:</label>
                <div class="controls">

                    <?php echo Form::text('segundo_nombre', 'class="span2"'); ?>

                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Primer Apellido:</label>
                <div class="controls">

                    <?php echo Form::text('primer_apellido', 'class="span2 req"'); ?>

                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Segundo Apellido:</label>
                <div class="controls">

                    <?php echo Form::text('segundo_apellido', 'class="span2"'). Form::hidden('ramas_id', null, $rama); ?>

                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <i class="icon-spinner icon-spin icon-2x" id="espere" style="display:none;"></i>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <button class="btn btn-primary" id="btnRegistrar">Registrar</button>
    </div>
</div>
<!-- Modal para borrar -->
<div id="mBorrar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Borrado...</h3>
    </div>
    <div class="modal-body">
        <p id="textAlert"></p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-danger" id="btnAlert">Borrar</button>
    </div>
</div>
<?php echo Tag::js('form'); ?>
<script type="text/javascript">
    var epoca = <?php echo ($registro)?'true':'false'; ?>;

    function spinnerRegistro() {
        $('#espere').toggle();
    }

    $('#btnRegistrar').on('click', function(evento) {
        evento.preventDefault();
        spinnerRegistro();
        var nac = $('#nac').val(), cedula = $('#cedula').val(), credencial = $('#credencial').val(), primer_nombre = $('#primer_nombre').val(), segundo_nombre = $('#segundo_nombre').val(), primer_apellido = $('#primer_apellido').val(), segundo_apellido = $('#segundo_apellido').val();
        $.post(
            '<?php echo PUBLIC_PATH; ?>jovenes/registrar/',
            {
                type: 'json',
                "registro[nacionalidad]": nac,
                "registro[cedula]": cedula,
                "registro[credencial]": credencial,
                "registro[primer_nombre]": primer_nombre,
                "registro[segundo_nombre]": segundo_nombre,
                "registro[primer_apellido]": primer_apellido,
                "registro[segundo_apellido]": segundo_apellido,
                "registro[ramas_id]": $('#ramas_id').val(),
                registrar: 'registrando'
            },
            function(data) {
                spinnerRegistro();
                if (data.status == "success") {
                    $('#vacio').remove();
                    var joven = '<tr>', nombre = primer_nombre+' '+segundo_nombre+' '+primer_apellido+' '+segundo_apellido;
                    joven += '<td>'+credencial+'</td>';
                    joven += '<td>'+nombre+'</td>';
                    joven += '<td class="text-center"> <a href="#" class="btn btn-primary editar"><i class="icon-edit"></i> Editar</a> </td>';
                    joven += (epoca)?'<td class="text-center"> <a href="#" class="btn btn-danger" data-nombre="'+nombre+'"><i class="icon-trash"></i> Borrar</a> </td>':'';
                    joven += '</tr>';
                    $('tbody').append(joven);
                    $('#ModalInsertar').modal('hide');
                    $('#Msj').sucessMsj(data.message);
                } else {
                    $('#alertPopup').errorMsj(data.message);
                }
            },
            'json'
        ).error(function() {
            spinnerRegistro();
            $('#Msj').errorMsj('Ha occurrido un error inesperado, actualice la página y vuelva a intentar');
            $('#ModalInsertar').modal('hide');
        });
    });

    // Editar 
    $('table').on('click', '.editar', function(e){
        e.preventDefault();
        // Code
    });

    $('table').on('click', '.btn-danger', function(e) {
        e.preventDefault();
        joven = $(this);
        id = joven.data('id');
        nombre = joven.data('nombre');
        fila = joven.parent().parent();
        $('#mBorrar').modal('show');
        $("#textAlert").html('Esta seguro que desea borrar '+nombre+'???');
        $("#btnAlert").on('click', function(e){
            e.preventDefault();
            $('#mBorrar').modal('hide');
            $('#Msj').infoMsj('<i class="icon-spinner icon-spin icon-2x"></i> Por favor espere...');
            $.post(
                '<?php echo PUBLIC_PATH; ?>jovenes/borrar/',
                {
                    type: 'json',
                    id: id
                },
                function(d) {
                    if (d.status=='success') {
                        fila.remove();
                        $('#Msj').sucessMsj(d.message);
                    } else {
                        $('#Msj').errorMsj(d.message);
                    }
                },
                'json'
            ).error(function() {
                $('#Msj').errorMsj('Ha occurrido un error inesperado, actualice la página y vuelva a intentar');
            });
        });
    });
</script>