

      <div class="row-fluid">
          <div class="span10 offset1">
            <?php View::content(); ?>
            <div class="hero-unit">
              <h1>Bienvenido Scouter</h1>
              <p>Esta es la página inicial de nuevo sistema en línea para concursos nacionales</p>
              <p><?php echo Html::link('instrucciones/','Insertar Jovenes»','class="btn btn-primary btn-large"'); ?> o <?php echo Html::link('instrucciones/','Importar desde un GPO »','class="btn btn-primary btn-large"'); ?></p>
            </div>
            <div class="span11">
              <p style="text-align:justify;">El laboratorio de Calidad no busca calificar a los grupos como buenos o malos, <strong>todos los grupos son buenos</strong>. Esta herramienta tiene la intención de fortalecer a <strong>los grupos que se quieren desarrollar</strong> y que están plenamente comprometidos en que el mejorar es una característica del Movimiento Scout.</p>

              <p>El laboratorio tiene dos propósitos principales:</p>
              <ul>
                <li><strong>Para tu Grupo:</strong> Que los dirigentes descubran puntos a mejorar y todos sus potenciales para luego establecer metas concretas de desarrollo del Grupo.</li>
                <li><strong>Para la Asociación:</strong> Que contemos con información detallada de los Grupos, para organizar mejor los Planes Nacionales, tomando en cuenta las necesidades particulares de los Grupos Scout.</li>
              </ul>
            </div>
          </div>
        </div>

