      <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span10 offset1">
                    <?php View::content(); ?>
                    <?php echo Html::img('cintillo.jpg', '', 'class="img-polaroid" id="cintillo" width="960px" height="173px"'); ?>
                </div>
                <div class="span5 offset1 cajas">
                    <h5>Datos Generales</h5>
                    <div class="cajitas" style="">
                        <div class="row">
                            <h4 class="text-center">Bienvenido Scter. <?php echo $usuario->primer_nombre,' ',$usuario->primer_apellido; ?></h4>
                            <p class="text-center"><b>Última visita:</b> <?php echo Toolkit::getHowLong(Load::model('log')->ultimaVisita()); ?></p>
                            <?php if( empty($usuario->region_id) ): ?><p class="text-center"><b>Nivel acceso:</b> Nacional</p><?php endif; ?>
                            <div style="width:400px; margin:auto;">
                                <div class="span2">
                                    <?php if( !empty($usuario->region_id) ): ?><p><b>Región:</b> <?php echo $usuario->region_nombre; ?></p><?php endif; ?>
                                    <?php if( !empty($usuario->grupos_id) ): ?><p><b>Grupo:</b> <?php echo $usuario->grupos_nombre; ?></p><?php endif; ?>
                                </div>
                                <div class="span2">
                                    <?php if( !empty($usuario->distrito_id) ): ?><p><b>Distrito:</b> <?php echo $usuario->distrito_nombre; ?></p><?php endif; ?>
                                    <?php if( !empty($usuario->ramas_id) ): ?><p><b>Unidad:</b> <?php echo $ramas; ?></p><?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="span5 cajas">
                    <h5>Últimas Actividades Reportadas</h5>
                    <div class="cajitas">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Fecha <a href="#" data-toggle="tooltip" data-placement="top" title="Fecha de realización"><i class="icon-question-sign"></i></a></th>
                                    <th>Actividad</th>
                                    <th>Lugar</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $ultimas = Load::model('actividades')->ultimasActividades();
                                if ( count($ultimas) == 0): ?>
                                <tr>
                                    <td colspan="3">No posee Actividades</td>
                                </tr>
                                <?php
                                else:
                                    foreach ($ultimas as $item):
                                ?>
                                <tr>
                                    <td><?php echo Toolkit::fecha($item->fecha); ?></td>
                                    <td><?php echo $item->nombre; ?></td>
                                    <td><?php echo $item->lugar; ?></td>
                                </tr>
                                <?php endforeach; endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
      </div>

      <script type="text/javascript">
      $('a').tooltip();
      </script>