      <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span10 offset1">
                    <?php View::content(); ?>
                    <?php echo Html::img('cintillo.png', '', 'class="img-polaroid" id="cintillo"'); ?>
                </div>



                <div class="span5 offset1 cajas">
                    <h5>Datos Generales</h5>
                    <div class="cajitas" style="">
                        <div class="row">
                            <h4 class="text-center">Bienvenido Scter. <?php echo $usuario->primer_nombre,' ',$usuario->primer_apellido; ?></h4>

                            <div style="width:400px; margin:auto;">
                                <div class="span2">
                                    <p><b>Región:</b> Falcón</p>
                                    <p><b>Distrito:</b> Paraguaná</p>
                                </div>
                                <div class="span2">
                                    <p><b>Grupo:</b> Nazareth</p>
                                    <p><b>Unidad:</b> Clan</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="span5 cajas">
                    <h5>Últimas Actividades Reportadas</h5>
                    <div class="cajitas">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Fecha</th>
                                    <th>Actividad</th>
                                    <th>Lugar</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $ultimas = Load::model('actividades')->ultimasActividades();
                                if ( count($ultimas) == 0): ?>
                                <tr>
                                    <td colspan="3">No posee Actividades</td>
                                </tr>
                                <?php
                                else:
                                    foreach ($ultimas as $item):
                                ?>
                                <tr>
                                    <td><?php echo Toolkit::fecha($item->fecha); ?></td>
                                    <td><?php echo $item->nombre; ?></td>
                                    <td><?php echo $item->lugar; ?></td>
                                </tr>
                                <?php endforeach; endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
      </div>