
      <form method="post" class="form-signin" action="bienvenida/">
        <h2 class="form-signin-heading">Bienvenido</h2>
        <input type="text" class="input-block-level" placeholder="Correo Electronico">
        <input type="password" class="input-block-level" placeholder="Contraseña">
        <button class="btn btn-large btn-primary" type="submit">Ingresar</button>
        <small>Sistema en línea de Concursos Nacionales<br>Desarrollado por Icter.us</small>
      </form>
