<div class="span10 offset1">
    <?php View::content(); ?>
    <div class="alert" id="Msj"></div>
    <?php if($nivel != 4): ?><a href="#ModalInsertar" role="button" data-toggle="modal" class="btn btn-success pull-right"><i class="icon-plus"></i> Nuevo</a><?php endif; ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Nombre</th>
                <th colspan="2" class="text-center">Opciones</th>
            </tr>
        </thead>
        <tbody>
        	<?php if(!count($lista)): ?>
        	<tr>
                <td colspan="5" class="text-center">No posee datos</td>
            </tr>
            <?php
            	else:
            		foreach ($lista as $item):
            			$link = 'estructura/'.($nivel+1).'/'.$item->id;
            			$ahref = Html::link($link, $item->nombre);
            ?>
            <tr>
                <td>&nbsp;</td>
                <td><?php echo  $ahref; ?></td>
                <td class="text-center">
                    <?php if ($item->estatus==1):
                        echo Html::link($ubicacion.'/desactivar/'.$item->id, '<i class="icon-frown"></i> Desactivar', 'class="btn btn-warning"');
                        else:
                            echo Html::link($ubicacion.'/activar/'.$item->id, '<i class="icon-smile"></i> Activar', 'class="btn btn-primary"');?>
                    <?php endif; ?>
                </td>
                <!-- <td class="text-center"> <a href="#" class="btn btn-primary"><i class="icon-edit"></i> Editar</a> </td> -->
                <td class="text-center">
                    <?php echo Html::link($ubicacion.'/borrar/'.$item->id, '<i class="icon-trash"></i> Borrar</a>', 'class="btn btn-danger" data-name="'.$item->nombre.'"');?>
            </tr>
            <?php
            		endforeach;
            	endif;
            ?>
        </tbody>
    </table>
</div>
<?php if($nivel != 4): ?>
<?php echo Tag::js('form'); ?>
<?php View::partial('estructura/modal_'.$nivel); ?>
<script type="text/javascript">
    $('a.btn-danger').on('click', function(e) {
        e.preventDefault();
        fila = $(this).parent().parent();
        link = $(this).attr('href');
        t = $(this).attr('data-name');
        console.log(this);
        $('#mBorrar').modal('show');
        $("#textAlert").html('Esta seguro que desea borrar '+t+'???');
        $("#btnAlert").on('click', function(e){
            e.preventDefault();
            borrar(link, fila);
        });
    });

    function borrar(url, fila) {
        $.getJSON(
            url+'/',
            {
                type: 'json'
            },
            function(d) {
                if (d.status=='valid') {
                    fila.remove();
                }
                $('#mBorrar').modal('hide');
                $('#Msj').sucessMsj(d.message);
            }
        );
    }

    // Desactivar
    $('a.btn-warning, a.btn-primary').on('click', function(e) {
        e.preventDefault();
        object = $(this);
        link = object.attr('href');
        $('#Msj').infoMsj("Por favor espere...");
        $.getJSON(
            link+'/',
            {
                type: 'json'
            },
            function(d) {
                if (d.status=='valid') {
                    if (object.hasClass('btn-warning')) {
                        nuevo = link.replace("/activar", "/desactivar");
                        object.attr('href', nuevo).removeClass('btn-warning').addClass('btn-primary').html('<i class="icon-smile"></i> Activar</td>');
                    } else {
                        nuevo = link.replace("/desactivar","/activar");
                        object.attr('href', nuevo).removeClass('btn-primary').addClass('btn-warning').html('<i class="icon-frown"></i> Desactivar');
                    }
                }
                $('#Msj').sucessMsj(d.message);
            }
        );
    });
</script>

<!-- Modal para borrar -->
<div id="mBorrar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Borrado...</h3>
    </div>
    <div class="modal-body">
        <p id="textAlert"></p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-danger" id="btnAlert">Save changes</button>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
    $('.alert').fadeOut();
</script>