<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta charset='<?php echo APP_CHARSET ?>' />
  <title><?php echo $title; ?></title>
  <!-- CDN de Bootstrap y Font-awesome -->
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
  <link href="http://cdn.scoutsfalcon.org/font.css" rel="stylesheet" type="text/css">
  <!--[if IE 7]>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome-ie7.min.css" rel="stylesheet">
  <![endif]-->
  <?php
  Tag::css('main');
  Tag::css('print', 'print');
  echo Html::IncludeCss();

  Html::headLink(PUBLIC_PATH.'img/favicon.ico' ,'rel="shortcut icon"');
  echo Html::includeHeadLinks();
  ?>
  <?php // echo Tag::js('jquery.min'); ?>
  <?php // echo Tag::js('bootstrap.min'); ?>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
    <?php View::partial('google_analytics'); ?>

    </head>
    <body>
      <div id="wrap">
        <div class="container">
            <div class="row">
                <?php View::partial('header'); ?>

                <?php View::content(); ?>
            </div>
        </div>
    </div>
    <div id="push"></div>
    <div class="container">
        <hr>
        <?php View::partial('footer'); ?>
    </div>

    <?php View::partial('modal_soporte'); ?>
</body>
</html>
