<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error - Base Admin</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- CDN de Bootstrap y Font-awesome -->
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

    <?php
    Tag::css('error');
    echo Html::IncludeCss();
    ?>

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
    <!--[if lt IE 9]>
      <?php echo Tag::js('html5shiv'); ?>
    <![endif]-->
    <!--[if IE 7]>
      <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome-ie7.min.css" rel="stylesheet">
    <![endif]-->


</head>

<body>
<div class="container">

    <div class="row">

        <div class="span12">

            <div class="error-container">
                <h1>Oops!</h1>

                <h2>404 Página No Encontrada</h2>

                <div class="error-details">
                    Lo sentimos, Página solicitado no encontrada!

                </div> <!-- /error-details -->

                <div class="error-actions">
                    <?php echo Html::link('', '<i class="icon-chevron-left icon-white"></i>&nbsp;Volver al Inicio', ' class="btn btn-large btn-primary"'); ?>
                </div> <!-- /error-actions -->

            </div> <!-- /error-container -->

        </div> <!-- /span12 -->

    </div> <!-- /row -->

</div> <!-- /container -->

<?php echo Tag::js('bootstrap/jquery'); ?>
<?php echo Tag::js('bootstrap/bootstrap.min'); ?>

</body>
</html>