    <?php View::content(); ?>
    <div class="span12">
        <div class="row">
        <?php $i=1; foreach ($objeto as $mes => $dias): ?>
            <div class="span4 cajas">
                <h5>
                    <?php echo ($mes_actual >= $i)?
                    $mes . ' <small>' . Html::link('actividades/nueva/'.$id.'/'.$i,'(Actividades)') . '</small>':
                    $mes . ' <small>(Aún no Disponible)</small>'; ?>
                </h5>
                <div class="cajitas">
                    <table class="table table-striped table-actividades">
                            <thead>
                                <tr>
                                    <th class="th-fecha">Fecha</th>
                                    <th>Actividades</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($dias as $dia): ?>
                                <tr>
                                    <td><?php echo $dia->fecha; ?></td>
                                    <td><?php echo $dia->nombre; ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                </div>
            </div>
        <?php if ( ($i%3)==0 ): ?>
        </div>
        <div class="row">
        <?php endif; $i++;  ?>
    <?php endforeach; ?>