    <?php View::content(); ?>
    <div class="span12">
        <div class="row">
        <?php $i=1; foreach ($objeto as $mes => $dias): $cantidad = count($dias)?>
            <div class="span4 cajas">
                <h5>
                    <?php
                    // A partir del 2014 solo se podrá reportar los 3 últimos meses en curso
                    echo $mes .
                    (
                        ( $ano_actual >= 2014 && ( ($mes_actual-2) <= $i  && $mes_actual >= $i ) )?
                        ' <small>' . Html::link('actividades/mes/'.$id.'/'.$i,'(Crear actividades)') . '</small>':
                        ' <small>(No disponible)</small>'
                    ); ?>
                </h5>
                <div class="cajitas">
                    <table class="table table-striped table-actividades">
                            <thead>
                                <tr>
                                    <th class="th-fecha text-center">Fecha</th>
                                    <th class="text-center">Actividades</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if ($cantidad != 0): foreach ($dias as $dia): ?>
                                <tr>
                                    <td>
                                        <?php
                                        if ($dia->fecha{4} == '-') {
                                            $fecha = explode('-', $dia->fecha); echo $fecha[2],'/',$fecha[1],'/',$fecha[0];
                                        } else {
                                            echo $dia->fecha;
                                        }
                                        ?>
                                    </td>
                                    <td><?php echo $dia->nombre; ?></td>
                                </tr>
                                <?php endforeach; else: ?>
                                <tr>
                                    <td colspan="2" class="text-center">Vacío</td>
                                </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                </div>
            </div>
        <?php if ( ($i%3)==0 ): ?>
        </div>
        <div class="row">
        <?php endif; $i++;  ?>
    <?php endforeach; ?>